### ISSUE TITLE
 Pas de licence : puis-je utiliser dictionnary.txt pour mon propre projet libre (licence MIT)

### ISSUE THREAD

**Issue by Naereen** [coco33920/Star-Trek-Pictionnary#1]
Bonjour @coco33920,
Je souhaiterai utiliser des mots des dictionnaires pour mon propre projet, qui sera distribué sous licence libre (licence MIT).
(https://github.com/Naereen/Free-dictionnaries-for-Pictionnary)
Votre projet n'inclut aucune information de licence, ce qui signifie par défaut qu'il non libre et sous votre copyright.
Puis-je utiliser vos dictionnaires dans mon projet ? Merci d'avance :pray: !
@Naereen

**Comment by vanilla-extracts** [comment]
Bien sûr !
Je serais contente!!

Bon courage pour votre projet

**Comment by Naereen** [comment]
Super, merci @coco33920 ! :vulcan_salute:
